version: '3'

services:
  db:
    image: postgres
    container_name: place-database-api
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: db
      PGDATA: /tmp
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/database-docker:/var/lib/postgresql/data 